// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// `migrations.seed` is what `prisma db seed` / `prisma migrate reset` run —
// note the explicit `--apply`: prisma/seed.ts defaults to a safe dry run
// when invoked directly (`tsx prisma/seed.ts`), so this flag is what makes
// the Prisma-triggered path actually write. See prisma/seed.ts's own
// comment for what it does and the dry-run/--apply pattern used throughout
// the seed/import scripts.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts --apply",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
